[program:archiver]
directory=/aeg_sw/work/users/ckd27546/develop/projects/hexitec/hxt_sw/src/hexitec-detector/control/
command=bash -c "source /hxt_sw/v-archiver-dev/bin/activate && odin_control --config /hxt_sw/src/hexitec-detector/control/config/archiver.cfg --http_addr 192.168.0.23" -DFOREGROUND
user=ckd27546
environment=HOME="/u/ckd27546",USER="ckd27546"
autostart=true
autorestart=true
stderr_logfile=/tmp/archiver.err
stdout_logfile=/tmp/archiver.out
