file_identifier "pva0";

table Bool   { value:  bool;   }
table Byte   { value:  byte;   }
table UByte  { value: ubyte;   }
table Short  { value:  short;  }
table UShort { value: ushort;  }
table Int    { value:  int;    }
table UInt   { value: uint;    }
table Long   { value:  long;   }
table ULong  { value: ulong;   }
table Float  { value:  float;  }
table Double { value:  double; }
table String { value:  string; }

table BoolArray   { value:  [bool];   }
table ByteArray   { value:  [byte];   }
table UByteArray  { value:  [ubyte];  }
table ShortArray  { value:  [short];  }
table UShortArray { value:  [ushort]; }
table IntArray    { value:  [int];    }
table UIntArray   { value:  [uint];   }
table LongArray   { value:  [long];   }
table ULongArray  { value:  [ulong];  }
table FloatArray  { value:  [float];  }
table DoubleArray { value:  [double]; }
table StringArray { value:  [string]; }

union AnyInner {
    Bool, Byte, UByte, Short, UShort, Int, UInt, Long, ULong, Float, Double, String,
    BoolArray, ByteArray, UByteArray, ShortArray, UShortArray, IntArray, UIntArray, LongArray, ULongArray, FloatArray, DoubleArray, StringArray
}

table AnyT {
  value: AnyInner;
}

enum AlarmStatus : ubyte {
    NONE,
    DEVICE,
    DRIVER,
    RECORD,
    DB,
    CONF,
    UNDEFINED,
    CLIENT
}

enum AlarmSeverity: ubyte {
    NONE,
    MINOR,
    MAJOR,
    INVALID,
    UNDEFINED
}

table AlarmT {
  severity: AlarmSeverity;
  status: AlarmStatus;
  message: string;
}

table TimeT {
  seconds_past_epoch: long;
  nanoseconds: int;
  user_tag: int;
}

enum DisplayForm : ubyte {
    DEFAULT,
    STRING,
    BINARY,
    DECIMAL,
    HEX,
    EXPONENTIAL,
    ENGINEERING
}

table DisplayT {
  limit_low: double;
  limit_high: double;
  description: string;
  units: string;
  precision: int;
  form: DisplayForm;
}

table ControlT {
  limit_low: double;
  limit_high: double;
  min_step: double;
}

table CodecT {
  name: string;
}

table DimensionT {
  size: int;
  offset: int;
  full_size: int;
  binning: int = 1;
  reverse: bool;
}

table NTAttribute {
  name: string;
  value: AnyT;
  tags: [string];
  descriptor: string;
  alarm: AlarmT;
  time: TimeT;
  source_type: int;
  source: string;
}

table NTNDArray {
  value: AnyT (required);
  codec: CodecT;
  compressed_size: long;
  uncompressed_size: long;
  dimension: [DimensionT];
  unique_id: int;
  data_time_stamp: TimeT;
  attribute: [NTAttribute];
  descriptor: string;
  alarm: AlarmT;
  time_stamp: TimeT;
  display: DisplayT;
}

table NTScalarAny {
  value: AnyT (required);
  descriptor: string;
  alarm: AlarmT;
  time_stamp: TimeT;
  display: DisplayT;
  control: ControlT;
}

table Column {
  value: AnyT;
}

table NTTable {
  labels: [string];
  value: [Column] (required);
  descriptor: string;
  alarm: AlarmT;
  time_stamp: TimeT;
  display: DisplayT;
}

table PulseID {
  value: uint64;
  time_stamp: double;
}

table XYData {
  x: NTScalarAny;
  y: NTScalarAny (required);
}

union PVType { NTScalarAny, NTNDArray, NTTable, XYData }

table PVData {
  data: PVType (required);
  source_name: string;
  pulse_id: PulseID;
}

root_type PVData;