name: Data Unit Tests

on: [push, pull_request]

env:
  BUILD_TYPE: Release
  CCACHE_VERSION: 3.7.7
  INSTALL_PREFIX: ${{ github.workspace }}/../install

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: "0"
    - name: Install boost
      run: |
        sudo apt-get install libboost-program-options-dev libboost-filesystem-dev 
        sudo apt-get install libboost-date-time-dev libboost-dev libboost-system-dev
        sudo apt-get install libboost-test-dev libboost-thread-dev libboost-regex-dev
        sudo apt-get install libzmq3-dev libpcap-dev liblog4cxx-dev libblosc-dev libhdf5-dev
    - name: Clone Odin-data
      run: |
        git clone https://github.com/odin-detector/odin-data.git
    - name: Build odin-data
      run: |
        cd odin-data
        echo "INSTALL_PREFIX is ${INSTALL_PREFIX}"
        mkdir -p $INSTALL_PREFIX
        mkdir build && cd build
        cmake -DCMAKE_INSTALL_PREFIX=$INSTALL_PREFIX ..
        make install VERBOSE=1
      env:
        MAKEFLAGS: "-j2"
    - name: Run frame receiver unit tests
      env:
        INSTALL_PREFIX: ${{ env.INSTALL_PREFIX }}
      run: |
        cd odin-data/build
        bin/frameReceiverTest
    - name: Run frame processor unit tests
      env:
        INSTALL_PREFIX: ${{ env.INSTALL_PREFIX }}
      run: |
        cd odin-data/build
        bin/frameProcessorTest
    - name: Build hexitec-detector 
      run: |
        cd data
        echo "INSTALL_PREFIX is ${INSTALL_PREFIX}"
        mkdir -p $INSTALL_PREFIX
        mkdir build && cd build
        cmake -DCMAKE_INSTALL_PREFIX=$INSTALL_PREFIX -DODINDATA_ROOT_DIR=$INSTALL_PREFIX ..
        make install VERBOSE=1
      env:
        MAKEFLAGS: "-j2"
    - name: Run odin-data frame integration test
      env:
        INSTALL_PREFIX: ${{ env.INSTALL_PREFIX }}
      run: |
        echo "INSTALL_PREFIX is ${INSTALL_PREFIX}"
        cd odin-data/build
        bin/odinDataTest --json=$INSTALL_PREFIX/test_config/hexitec2x2-average.json
        echo "Python version:"
        python --version
        pip install numpy
        pip install h5py
        pip install nose
        echo "Check processed_frames dataset as expected"
        python ${INSTALL_PREFIX}/test_config/dataset_check.py --filename 2x2_test_000001.h5 

    # - name: Slack Notification
    #   uses: rtCamp/action-slack-notify@v2
    #   env:
    #     SLACK_CHANNEL: hexitec
    #     SLACK_COLOR: ${{ job.status }}
    #     SLACK_ICON: https://avatars.githubusercontent.com/odin-detector?size=48
    #     SLACK_TITLE: Test hexitec CI action completed
    #     SLACK_USERNAME: odin-detector
    #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }} 
